### ISSUE TITLE
Schema Warnings from Plugin

### ISSUE THREAD

**Issue by bradymwilliams** [SimeonGriggs/sanity-plugin-availability#4]
Seeing 3 schema warnings with default installation of the plugin.

![image](https://user-images.githubusercontent.com/7980606/220997801-b7471a5b-2181-4f30-9ed0-9cc60a4e70c6.png)

**Comment by SimeonGriggs** [comment]
This is fixed in the newly released 1.0.1. 

Thanks for reporting!
